/**
 * Expo config plugin: iOS CarPlay scene wiring for react-native-carplay.
 *
 * CarPlay audio apps must adopt UIKit "scenes": one scene for the phone UI,
 * one for the car display. react-native-carplay provides the native bridge
 * (RNCarPlay.connect/disconnect) but the app must supply the scene manifest
 * and delegates — that's what this plugin generates at prebuild:
 *
 *  1. Info.plist: UIApplicationSceneManifest (phone scene + CarPlay scene)
 *  2. AppDelegate.swift: appends PhoneSceneDelegate + CarSceneDelegate classes
 *
 * ⚠️ TESTME: this is the highest-risk native codegen in the project. It follows
 * the react-native-carplay documented pattern for RN 0.8x scene setup, but it
 * could NOT be compiled locally (no Xcode on this machine). First EAS iOS build
 * + the CarPlay simulator check MUST verify it. If the iOS build fails here,
 * remove "./plugins/withCarPlayScenes" from app.json plugins to unblock the
 * phone app, and iterate on this plugin against the real compiler output.
 */
const { withInfoPlist, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ---------- 1) Info.plist scene manifest ----------
function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: true,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Phone',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).PhoneSceneDelegate',
          },
        ],
        CPTemplateApplicationSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'CarPlay',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).CarSceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });
}

// ---------- 2) Scene delegate classes appended to AppDelegate.swift ----------
const SCENE_DELEGATES = `

// ============================================================================
// CarPlay scene wiring — generated by plugins/withCarPlayScenes.js
// ============================================================================
import CarPlay

/// Phone scene: hosts the normal React Native UI once scenes are enabled.
/// With a scene manifest present, UIKit routes window creation here instead
/// of the classic AppDelegate path.
public class PhoneSceneDelegate: UIResponder, UIWindowSceneDelegate {
  public var window: UIWindow?

  public func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    let window = UIWindow(windowScene: windowScene)
    self.window = window

    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }

    if let existingRoot = appDelegate.window?.rootViewController {
      // RN was already started by AppDelegate at launch — adopt its root view.
      window.rootViewController = existingRoot
    } else {
      // Fallback: start React Native into this window.
      appDelegate.reactNativeFactory?.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: nil
      )
    }
    appDelegate.window = window
    window.makeKeyAndVisible()
  }
}

/// Car scene: hands the CarPlay interface controller to react-native-carplay,
/// which then renders the templates our CarPlayService.ts sets up.
public class CarSceneDelegate: UIResponder, CPTemplateApplicationSceneDelegate {
  public func templateApplicationScene(
    _ templateApplicationScene: CPTemplateApplicationScene,
    didConnect interfaceController: CPInterfaceController
  ) {
    RNCarPlay.connect(
      with: interfaceController,
      window: templateApplicationScene.carWindow
    )
  }

  public func templateApplicationScene(
    _ templateApplicationScene: CPTemplateApplicationScene,
    didDisconnectInterfaceController interfaceController: CPInterfaceController
  ) {
    RNCarPlay.disconnect()
  }
}
`;

function withSceneDelegates(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot;
      // Find AppDelegate.swift inside the app target folder
      const appName = cfg.modRequest.projectName;
      const candidates = [
        path.join(iosRoot, appName, 'AppDelegate.swift'),
      ];
      const target = candidates.find((p) => fs.existsSync(p));
      if (!target) {
        throw new Error(
          `withCarPlayScenes: AppDelegate.swift not found (looked in ${candidates.join(', ')})`
        );
      }
      let src = fs.readFileSync(target, 'utf8');
      if (!src.includes('CarPlay scene wiring')) {
        src += SCENE_DELEGATES;
        fs.writeFileSync(target, src);
      }
      return cfg;
    },
  ]);
}

module.exports = function withCarPlayScenes(config) {
  config = withSceneManifest(config);
  config = withSceneDelegates(config);
  return config;
};
